version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: athena-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: athena
    ports:
      - '3306:3306'
    volumes:
      - athena_mysql_data:/var/lib/mysql
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  athena_mysql_data:
